package com.richey.gtbankapp;


import com.richey.gtbankapp.dto.AccountRequest;
import com.richey.gtbankapp.dto.AccountResponse;
import com.richey.gtbankapp.model.Account;
import com.richey.gtbankapp.model.User;
import com.richey.gtbankapp.model.UserRole;
import com.richey.gtbankapp.repo.AccountRepo;
import com.richey.gtbankapp.repo.UserRepo;
import com.richey.gtbankapp.security.SecurityUtils;
import com.richey.gtbankapp.service.AccountServiceImpl;
import org.apache.coyote.Response;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpStatus;
import org.springframework.web.server.ResponseStatusException;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;


import java.util.List;
import java.util.Optional;

import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class AccountServiceTest {

    @Mock
    private UserRepo userRepo;
    @Mock
    private AccountRepo accountRepo;

    @Mock
    private  SecurityUtils securityUtils;

    @InjectMocks
    private AccountServiceImpl accountService;


    private User user;
    private Account account;



    @BeforeEach
    void setUp(){
        user = User.builder()
                .id(1L)
                .firstName("John")
                .lastName("Doe")
                .email("johndoe@gmail.com")
                .password("password")
                .role(UserRole.ROLE_USER)
                .build();

        account = Account.builder()
                .iban("TN5904018104004942712345")
                .user(user)
                .build();

    }


    @Test
    @DisplayName("createAccount")
    void createAccount_success(){
        AccountRequest request = new AccountRequest("TN5904018104004942712345", 1L);
        when(userRepo.findById(1L)).thenReturn(Optional.of(user));
        when(accountRepo.existsByUserId(1L)).thenReturn(false);
        when(accountRepo.existsByIban(anyString())).thenReturn(false);
        when(accountRepo.save(any(Account.class))).thenAnswer(inv -> inv.getArgument(0));


        AccountResponse response = accountService.createAccount(request);

        ArgumentCaptor<Account> captor = ArgumentCaptor.forClass(Account.class);
        verify(accountRepo).save(captor.capture());
        Account saved = captor.getValue();

        assertSame(user, saved.getUser());
        assertNotNull(saved.getIban());
        assertTrue(saved.getIban().startsWith("TN"));

        assertEquals(saved.getIban(), response.iban());
        assertEquals("John", response.firstName());
        assertEquals("Doe", response.lastName());
        assertEquals("johndoe@gmail.com", response.email());
        assertFalse(response.locked());
    }

    @Test
    @DisplayName("If User does not exists")
    void createAccount_userNotFound() {
        when(userRepo.findById(99L)).thenReturn(Optional.empty());

        ResponseStatusException ex = assertThrows(ResponseStatusException.class,
                () -> accountService.createAccount(new AccountRequest("TN5904018104004942712345",  99L)));

        assertEquals(HttpStatus.NOT_FOUND, ex.getStatusCode());
        verify(accountRepo, never()).save(any());
    }

    @Test
    @DisplayName("409: User already has account")
    void createAccount_409(){
        when(userRepo.findById(1L)).thenReturn(Optional.of(user));
        when(accountRepo.existsByUserId(1L)).thenReturn(true);

        ResponseStatusException ex = assertThrows(ResponseStatusException.class, () ->
                accountService.createAccount(new AccountRequest("TN5904018104004942712345", 1L)));

        assertEquals(HttpStatus.CONFLICT, ex.getStatusCode());
        verify(accountRepo, never()).save(any());
        verify(accountRepo, never()).existsByIban(anyString());
    }


    @Test
    @DisplayName("Create Account: Iban already exists")
    @Disabled("Need to Handle AutoGenerated Iban")
    void createAccount_existingIban(){
        when(userRepo.findById(1L)).thenReturn(Optional.of(user));
        when(accountRepo.existsByUserId(1L)).thenReturn(false);
        when(accountRepo.existsByIban(anyString())).thenReturn(true, false);
        when(accountRepo.save(any(Account.class))).thenAnswer(inv -> inv.getArgument(0));

        // Theory: generate Iban will generate new random Iban automatically
        accountService.createAccount(new AccountRequest("TN71 8500 1369 2460 3382 4471", 1L));

        ArgumentCaptor<String> ibanCheck = ArgumentCaptor.forClass(String.class);

        verify(accountRepo, times(2)).existsByIban(ibanCheck.capture());
        ArgumentCaptor<Account> saved = ArgumentCaptor.forClass(Account.class);
        verify(accountRepo).save(saved.capture());


        String ibanColl = ibanCheck.getAllValues().get(0);
        String iban_Free = ibanCheck.getAllValues().get(1);

        assertNotEquals(ibanColl, saved.getValue().getIban());
        assertEquals(iban_Free, saved.getValue().getIban());
    }

    // Toggle
    @Test
    @DisplayName("Lock Account")
    void toggleAccount(){
        account.setLocked(true);
        when(accountRepo.findById(1L)).thenReturn(Optional.of(account));
        when(accountRepo.save(any(Account.class))).thenAnswer(invocation
                -> invocation.getArgument(0));

        // Toggle
        AccountResponse response = accountService.toggleAccountLock(1L);
        assertFalse(response.locked());
    }

    // Get All
    @Test
    @DisplayName("Get All Accounts")
    void getAllAccount_success(){
        Pageable pageable = PageRequest.of(0, 10);
        Page<Account> page = new PageImpl<>(List.of(account), pageable, 1);
        when(accountRepo.findAll(pageable)).thenReturn(page);
        Page<AccountResponse> res = accountService.getAllAccount(pageable);

        assertEquals(1, res.getTotalElements());
        AccountResponse accountList = res.getContent().get(0); // Get the first element

        assertEquals("TN5904018104004942712345", accountList.iban());
        assertEquals("johndoe@gmail.com", accountList.email());
    }

    @Test
    @DisplayName("Get Account By Id")
    void getAccountById(){
        when(accountRepo.findById(1L)).thenReturn(Optional.of(account));
        AccountResponse response = accountService.getAccountById(1L);

        assertEquals("TN5904018104004942712345", response.iban());
        assertEquals("John", response.firstName());
        assertEquals("johndoe@gmail.com", response.email());
    }

    @Test
    @DisplayName("Get Account By Id - 404")
    void getAccountById_404(){
        when(accountRepo.findById(10L)).thenReturn(Optional.empty());
        ResponseStatusException ex = assertThrows(ResponseStatusException.class,
                () -> accountService.getAccountById(10L));

        assertEquals(HttpStatus.NOT_FOUND, ex.getStatusCode());
    }

    @Test
    @DisplayName("Get Account of User")
    void getAccountUser(){
        when(securityUtils.getCurrentUserId()).thenReturn(1L);
        when(accountRepo.findByUserId(1L)).thenReturn(Optional.of(account));
        AccountResponse accountResponse = accountService.getUserAccount();
        assertEquals("TN5904018104004942712345", accountResponse.iban());

    }

    // If user does not have account , return error
    @Test
    @DisplayName("404, current user doesnt have account")
    void getUserAccount(){
        when(securityUtils.getCurrentUserId()).thenReturn(1L);
        when(accountRepo.findByUserId(1L)).thenReturn(Optional.empty());

        ResponseStatusException ex = assertThrows(ResponseStatusException.class,
                () -> accountService.getUserAccount()
                );

        assertEquals(HttpStatus.NOT_FOUND, ex.getStatusCode());
    }
}
